# Generated by Django 3.2.9 on 2021-11-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aljazeera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='news id')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('title_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('record_time', models.DateTimeField(auto_now=True)),
                ('news_time', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Aljazeera News',
                'verbose_name_plural': 'Aljazeera News',
            },
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='news id')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('title_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('record_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Art News',
                'verbose_name_plural': 'Art News',
            },
        ),
        migrations.CreateModel(
            name='BBC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='news id')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('title_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('record_time', models.DateTimeField(auto_now=True)),
                ('news_time', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'BBC News',
                'verbose_name_plural': 'BBC News',
            },
        ),
        migrations.CreateModel(
            name='CNN',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='news id')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('title_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('record_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CNN News',
                'verbose_name_plural': 'CNN News',
            },
        ),
        migrations.CreateModel(
            name='FirstNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='news id')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('title_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('record_time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'verbose_name': 'First News',
                'verbose_name_plural': 'First News',
            },
        ),
        migrations.CreateModel(
            name='Gizmodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='news id')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('title_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('record_time', models.DateTimeField(auto_now=True)),
                ('news_time', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
                ('author_link', models.URLField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Gizmodo News',
                'verbose_name_plural': 'Gizmodo News',
            },
        ),
        migrations.CreateModel(
            name='HackerNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='news id')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('title_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('record_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hacker News',
                'verbose_name_plural': 'Hacker News',
            },
        ),
        migrations.CreateModel(
            name='SkySport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='news id')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('title_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('record_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sky Sports News',
                'verbose_name_plural': 'Sky Sports News',
            },
        ),
        migrations.CreateModel(
            name='TechCrunch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='news id')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('title_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('record_time', models.DateTimeField(auto_now=True)),
                ('news_time', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'TechCrunch News',
                'verbose_name_plural': 'TechCrunch News',
            },
        ),
        migrations.CreateModel(
            name='TheGuardian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='news id')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('title_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('record_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'The Guardian News',
                'verbose_name_plural': 'The Guardian News',
            },
        ),
        migrations.CreateModel(
            name='TVN24',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='news id')),
                ('title', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
                ('title_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('comment', models.CharField(blank=True, max_length=1000, null=True)),
                ('comment_link', models.URLField(blank=True, max_length=1000, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
                ('record_time', models.DateTimeField(auto_now=True)),
                ('news_time', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'TVN24 News',
                'verbose_name_plural': 'TVN24 News',
            },
        ),
    ]
