# Generated by Django 3.2.9 on 2021-11-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_alter_bbc_news_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbc',
            options={'verbose_name': 'BBC News', 'verbose_name_plural': '     BBC News'},
        ),
        migrations.AlterModelOptions(
            name='cnn',
            options={'verbose_name': 'CNN News', 'verbose_name_plural': '    CNN News'},
        ),
        migrations.AlterModelOptions(
            name='skysport',
            options={'verbose_name': 'Sky Sports News', 'verbose_name_plural': '   Sky Sports News'},
        ),
        migrations.AlterModelOptions(
            name='techcrunch',
            options={'verbose_name': 'TechCrunch News', 'verbose_name_plural': ' TechCrunch News'},
        ),
        migrations.AddField(
            model_name='firstnews',
            name='detail_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
