# Generated by Django 3.2.9 on 2021-11-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_auto_20211119_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bbc',
            options={'ordering': ['-record_time'], 'verbose_name': 'BBC News', 'verbose_name_plural': '     BBC News'},
        ),
        migrations.AlterField(
            model_name='aljazeera',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='art',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bbc',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cnn',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='firstnews',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gizmodo',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hackernews',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='skysport',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='techcrunch',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='theguardian',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tvn24',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
