# Generated by Django 3.2.9 on 2021-11-19 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0006_auto_20211119_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hackernews',
            options={'verbose_name': 'Hacker News', 'verbose_name_plural': ' Hacker News'},
        ),
    ]
